### PR TITLE
Updated to Node 8.1.2

### PR DESCRIPTION
**Pull request by mcollina**
@addaleax Can you have a look while this fails in Node < 8?

cc @calvinmetcalf

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
it's actually the current one too that fails in node 8

**Comment by mcollina** [comment]
the current one fails on node >= 8, while this one fails on Node < 8

**Comment by calvinmetcalf** [comment]
ah, confusing breaking change of some sort

**Comment by mcollina** [comment]
So, I think it might be related to something low level, and we need to abstract the test.

**Comment by mcollina** [comment]
I think this the source of the problem: https://github.com/nodejs/node/commit/24ef1e67757514db9ee1aeded555d4fb336ca817

I think we should just conditionally pick the right test depending on the version of V8 we running against.

**Comment by mcollina** [comment]
I have disabled the V8-dependant checks.

**Comment by mcollina** [comment]
Closed in favor of #6

**Pull request closed without merging**
